# Production Secrets for News API
apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: production
type: Opaque
data:
  username: cG9zdGdyZXM=  # postgres
  password: cHJvZF9uZXdzX2RiX3Bhc3N3b3JkXzIwMjQ=  # prod_news_db_password_2024

---
apiVersion: v1
kind: Secret
metadata:
  name: redis-secret
  namespace: production
type: Opaque
data:
  password: cHJvZF9yZWRpc19wYXNzd29yZF8yMDI0  # prod_redis_password_2024

---
apiVersion: v1
kind: Secret
metadata:
  name: news-api-secret
  namespace: production
type: Opaque
data:
  jwt-secret: cHJvZF9qd3Rfc2VjcmV0X25ld3NfYXBpXzIwMjQ=  # prod_jwt_secret_news_api_2024
  api-key: cHJvZF9hcGlfa2V5X25ld3NfMjAyNA==  # prod_api_key_news_2024

---
apiVersion: v1
kind: Secret
metadata:
  name: tls-secret
  namespace: production
type: kubernetes.io/tls
data:
  # These should be replaced with actual TLS certificates in production
  tls.crt: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0t  # placeholder cert
  tls.key: LS0tLS1CRUdJTiBQUklWQVRFIEtFWS0tLS0t  # placeholder key
