apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    orgId: 1
    uid: prometheus
    url: http://prod_prometheus:9090
    basicAuth: false
    isDefault: true
    version: 1
    editable: true
