run:
  timeout: 10m

linters:
  enable:
    - bodyclose
    - errcheck
    - gosec
    - gosimple
    - govet
    - ineffassign
    - misspell
    - staticcheck
    - typecheck
    - unused
    - revive
    - gofmt
    - goimports
