global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'news-api-prod'
    static_configs:
      - targets: ['prod_api:8080']
    metrics_path: /metrics
    scrape_interval: 5s

  - job_name: 'jaeger-prod'
    static_configs:
      - targets: ['prod_jaeger:14269']

  - job_name: 'elasticsearch-prod'
    static_configs:
      - targets: ['prod_elasticsearch:9200']
    metrics_path: /_prometheus/metrics
    scrape_interval: 30s
